version: "3.9"
services: 
  web:
    #image: rubenrr/webapp08:3.0 #if you want to use a concrete image
    build: 
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - 8443:8443
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/gymguru
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    restart: on-failure
  db:
    image: mysql:8.0.36
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=gymguru
  
    